In [2]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.2.1.tar.gz (281.4 MB)
     |████████████████████████████████| 281.4 MB 30 kB/s
Collecting py4j==0.10.9.3
  Downloading py4j-0.10.9.3-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 62.0 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.2.1-py2.py3-none-any.whl size=281853642 sha256=57c1b119f86327cde7fad2faa7308933c26bdbbedd63d094bcf3db7d53129eb6
  Stored in directory: /root/.cache/pip/wheels/9f/f5/07/7cd8017084dce4e93e84e92efd1e1d5334db05f2e83bcef74f
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.3 pyspark-3.2.1

In [3]:
import pyspark
from pyspark.sql import SparkSession

In [4]:
spark = SparkSession.builder.getOrCreate()

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
df = spark.read.csv('/content/drive/MyDrive/Colab Notebooks/CarPrice_Assignment (1).csv')
df.show()        # displaying top 20 rows

+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+---------+
|   _c0|      _c1|                 _c2|     _c3|       _c4|       _c5|        _c6|       _c7|           _c8|      _c9|     _c10|    _c11|     _c12|      _c13|      _c14|          _c15|      _c16|      _c17|     _c18|  _c19|            _c20|      _c21|   _c22|   _c23|      _c24|     _c25|
+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+---------+
|car_ID|symboling|             CarName|fueltype|aspiration|doornumber|    carbody|drivewheel|enginelocation|wheelbase|carlength|carwidth|carheight|curbweight|enginetype|cylindernumber|enginesize|fuelsystem|boreratio|stroke|compressionratio|horsepower|peakrpm|citympg|highwaympg|    price|
|     1|        3|  alfa-romero giulia|     gas|       std|       two|convertible|       rwd|         front|     88.6|    168.8|    64.1|     48.8|      2548|      dohc|          four|       130|      mpfi|     3.47|  2.68|               9|       111|   5000|     21|        27|    13495|
|     2|        3| alfa-romero stelvio|     gas|       std|       two|convertible|       rwd|         front|     88.6|    168.8|    64.1|     48.8|      2548|      dohc|          four|       130|      mpfi|     3.47|  2.68|               9|       111|   5000|     21|        27|    16500|
|     3|        1|alfa-romero Quadr...|     gas|       std|       two|  hatchback|       rwd|         front|     94.5|    171.2|    65.5|     52.4|      2823|      ohcv|           six|       152|      mpfi|     2.68|  3.47|               9|       154|   5000|     19|        26|    16500|
|     4|        2|         audi 100 ls|     gas|       std|      four|      sedan|       fwd|         front|     99.8|    176.6|    66.2|     54.3|      2337|       ohc|          four|       109|      mpfi|     3.19|   3.4|              10|       102|   5500|     24|        30|    13950|
|     5|        2|          audi 100ls|     gas|       std|      four|      sedan|       4wd|         front|     99.4|    176.6|    66.4|     54.3|      2824|       ohc|          five|       136|      mpfi|     3.19|   3.4|               8|       115|   5500|     18|        22|    17450|
|     6|        2|            audi fox|     gas|       std|       two|      sedan|       fwd|         front|     99.8|    177.3|    66.3|     53.1|      2507|       ohc|          five|       136|      mpfi|     3.19|   3.4|             8.5|       110|   5500|     19|        25|    15250|
|     7|        1|          audi 100ls|     gas|       std|      four|      sedan|       fwd|         front|    105.8|    192.7|    71.4|     55.7|      2844|       ohc|          five|       136|      mpfi|     3.19|   3.4|             8.5|       110|   5500|     19|        25|    17710|
|     8|        1|           audi 5000|     gas|       std|      four|      wagon|       fwd|         front|    105.8|    192.7|    71.4|     55.7|      2954|       ohc|          five|       136|      mpfi|     3.19|   3.4|             8.5|       110|   5500|     19|        25|    18920|
|     9|        1|           audi 4000|     gas|     turbo|      four|      sedan|       fwd|         front|    105.8|    192.7|    71.4|     55.9|      3086|       ohc|          five|       131|      mpfi|     3.13|   3.4|             8.3|       140|   5500|     17|        20|    23875|
|    10|        0| audi 5000s (diesel)|     gas|     turbo|       two|  hatchback|       4wd|         front|     99.5|    178.2|    67.9|       52|      3053|       ohc|          five|       131|      mpfi|     3.13|   3.4|               7|       160|   5500|     16|        22|17859.167|
|    11|        2|            bmw 320i|     gas|       std|       two|      sedan|       rwd|         front|    101.2|    176.8|    64.8|     54.3|      2395|       ohc|          four|       108|      mpfi|      3.5|   2.8|             8.8|       101|   5800|     23|        29|    16430|
|    12|        0|            bmw 320i|     gas|       std|      four|      sedan|       rwd|         front|    101.2|    176.8|    64.8|     54.3|      2395|       ohc|          four|       108|      mpfi|      3.5|   2.8|             8.8|       101|   5800|     23|        29|    16925|
|    13|        0|              bmw x1|     gas|       std|       two|      sedan|       rwd|         front|    101.2|    176.8|    64.8|     54.3|      2710|       ohc|           six|       164|      mpfi|     3.31|  3.19|               9|       121|   4250|     21|        28|    20970|
|    14|        0|              bmw x3|     gas|       std|      four|      sedan|       rwd|         front|    101.2|    176.8|    64.8|     54.3|      2765|       ohc|           six|       164|      mpfi|     3.31|  3.19|               9|       121|   4250|     21|        28|    21105|
|    15|        1|              bmw z4|     gas|       std|      four|      sedan|       rwd|         front|    103.5|      189|    66.9|     55.7|      3055|       ohc|           six|       164|      mpfi|     3.31|  3.19|               9|       121|   4250|     20|        25|    24565|
|    16|        0|              bmw x4|     gas|       std|      four|      sedan|       rwd|         front|    103.5|      189|    66.9|     55.7|      3230|       ohc|           six|       209|      mpfi|     3.62|  3.39|               8|       182|   5400|     16|        22|    30760|
|    17|        0|              bmw x5|     gas|       std|       two|      sedan|       rwd|         front|    103.5|    193.8|    67.9|     53.7|      3380|       ohc|           six|       209|      mpfi|     3.62|  3.39|               8|       182|   5400|     16|        22|    41315|
|    18|        0|              bmw x3|     gas|       std|      four|      sedan|       rwd|         front|      110|      197|    70.9|     56.3|      3505|       ohc|           six|       209|      mpfi|     3.62|  3.39|               8|       182|   5400|     15|        20|    36880|
|    19|        2|    chevrolet impala|     gas|       std|       two|  hatchback|       fwd|         front|     88.4|    141.1|    60.3|     53.2|      1488|         l|         three|        61|      2bbl|     2.91|  3.03|             9.5|        48|   5100|     47|        53|     5151|
+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+---------+
only showing top 20 rows

In [7]:
df.head()

Row(_c0='car_ID', _c1='symboling', _c2='CarName', _c3='fueltype', _c4='aspiration', _c5='doornumber', _c6='carbody', _c7='drivewheel', _c8='enginelocation', _c9='wheelbase', _c10='carlength', _c11='carwidth', _c12='carheight', _c13='curbweight', _c14='enginetype', _c15='cylindernumber', _c16='enginesize', _c17='fuelsystem', _c18='boreratio', _c19='stroke', _c20='compressionratio', _c21='horsepower', _c22='peakrpm', _c23='citympg', _c24='highwaympg', _c25='price')

In [8]:
df.show(5)

+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+
|   _c0|      _c1|                 _c2|     _c3|       _c4|       _c5|        _c6|       _c7|           _c8|      _c9|     _c10|    _c11|     _c12|      _c13|      _c14|          _c15|      _c16|      _c17|     _c18|  _c19|            _c20|      _c21|   _c22|   _c23|      _c24| _c25|
+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+
|car_ID|symboling|             CarName|fueltype|aspiration|doornumber|    carbody|drivewheel|enginelocation|wheelbase|carlength|carwidth|carheight|curbweight|enginetype|cylindernumber|enginesize|fuelsystem|boreratio|stroke|compressionratio|horsepower|peakrpm|citympg|highwaympg|price|
|     1|        3|  alfa-romero giulia|     gas|       std|       two|convertible|       rwd|         front|     88.6|    168.8|    64.1|     48.8|      2548|      dohc|          four|       130|      mpfi|     3.47|  2.68|               9|       111|   5000|     21|        27|13495|
|     2|        3| alfa-romero stelvio|     gas|       std|       two|convertible|       rwd|         front|     88.6|    168.8|    64.1|     48.8|      2548|      dohc|          four|       130|      mpfi|     3.47|  2.68|               9|       111|   5000|     21|        27|16500|
|     3|        1|alfa-romero Quadr...|     gas|       std|       two|  hatchback|       rwd|         front|     94.5|    171.2|    65.5|     52.4|      2823|      ohcv|           six|       152|      mpfi|     2.68|  3.47|               9|       154|   5000|     19|        26|16500|
|     4|        2|         audi 100 ls|     gas|       std|      four|      sedan|       fwd|         front|     99.8|    176.6|    66.2|     54.3|      2337|       ohc|          four|       109|      mpfi|     3.19|   3.4|              10|       102|   5500|     24|        30|13950|
+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+
only showing top 5 rows

In [9]:
df.dtypes

[('_c0', 'string'),
 ('_c1', 'string'),
 ('_c2', 'string'),
 ('_c3', 'string'),
 ('_c4', 'string'),
 ('_c5', 'string'),
 ('_c6', 'string'),
 ('_c7', 'string'),
 ('_c8', 'string'),
 ('_c9', 'string'),
 ('_c10', 'string'),
 ('_c11', 'string'),
 ('_c12', 'string'),
 ('_c13', 'string'),
 ('_c14', 'string'),
 ('_c15', 'string'),
 ('_c16', 'string'),
 ('_c17', 'string'),
 ('_c18', 'string'),
 ('_c19', 'string'),
 ('_c20', 'string'),
 ('_c21', 'string'),
 ('_c22', 'string'),
 ('_c23', 'string'),
 ('_c24', 'string'),
 ('_c25', 'string')]

In [10]:
df.count()

206

In [11]:
from pyspark.sql.functions import col,isnan, when, count
df.select([count(when(isnan(c) | col(c).isNull(), c)).alias(c) for c in df.columns]
   ).show()

+---+---+---+---+---+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
|_c0|_c1|_c2|_c3|_c4|_c5|_c6|_c7|_c8|_c9|_c10|_c11|_c12|_c13|_c14|_c15|_c16|_c17|_c18|_c19|_c20|_c21|_c22|_c23|_c24|_c25|
+---+---+---+---+---+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
+---+---+---+---+---+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+

In [12]:

#Find count for selected columns

df_Columns=["_c1","_c2"]
df.select([count(when(isnan(c) | col(c).isNull(), c)).alias(c) for c in df_Columns]
   ).show()

+---+---+
|_c1|_c2|
+---+---+
|  0|  0|
+---+---+

In [13]:
df.fillna(value=0).show()

+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+---------+
|   _c0|      _c1|                 _c2|     _c3|       _c4|       _c5|        _c6|       _c7|           _c8|      _c9|     _c10|    _c11|     _c12|      _c13|      _c14|          _c15|      _c16|      _c17|     _c18|  _c19|            _c20|      _c21|   _c22|   _c23|      _c24|     _c25|
+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+---------+
|car_ID|symboling|             CarName|fueltype|aspiration|doornumber|    carbody|drivewheel|enginelocation|wheelbase|carlength|carwidth|carheight|curbweight|enginetype|cylindernumber|enginesize|fuelsystem|boreratio|stroke|compressionratio|horsepower|peakrpm|citympg|highwaympg|    price|
|     1|        3|  alfa-romero giulia|     gas|       std|       two|convertible|       rwd|         front|     88.6|    168.8|    64.1|     48.8|      2548|      dohc|          four|       130|      mpfi|     3.47|  2.68|               9|       111|   5000|     21|        27|    13495|
|     2|        3| alfa-romero stelvio|     gas|       std|       two|convertible|       rwd|         front|     88.6|    168.8|    64.1|     48.8|      2548|      dohc|          four|       130|      mpfi|     3.47|  2.68|               9|       111|   5000|     21|        27|    16500|
|     3|        1|alfa-romero Quadr...|     gas|       std|       two|  hatchback|       rwd|         front|     94.5|    171.2|    65.5|     52.4|      2823|      ohcv|           six|       152|      mpfi|     2.68|  3.47|               9|       154|   5000|     19|        26|    16500|
|     4|        2|         audi 100 ls|     gas|       std|      four|      sedan|       fwd|         front|     99.8|    176.6|    66.2|     54.3|      2337|       ohc|          four|       109|      mpfi|     3.19|   3.4|              10|       102|   5500|     24|        30|    13950|
|     5|        2|          audi 100ls|     gas|       std|      four|      sedan|       4wd|         front|     99.4|    176.6|    66.4|     54.3|      2824|       ohc|          five|       136|      mpfi|     3.19|   3.4|               8|       115|   5500|     18|        22|    17450|
|     6|        2|            audi fox|     gas|       std|       two|      sedan|       fwd|         front|     99.8|    177.3|    66.3|     53.1|      2507|       ohc|          five|       136|      mpfi|     3.19|   3.4|             8.5|       110|   5500|     19|        25|    15250|
|     7|        1|          audi 100ls|     gas|       std|      four|      sedan|       fwd|         front|    105.8|    192.7|    71.4|     55.7|      2844|       ohc|          five|       136|      mpfi|     3.19|   3.4|             8.5|       110|   5500|     19|        25|    17710|
|     8|        1|           audi 5000|     gas|       std|      four|      wagon|       fwd|         front|    105.8|    192.7|    71.4|     55.7|      2954|       ohc|          five|       136|      mpfi|     3.19|   3.4|             8.5|       110|   5500|     19|        25|    18920|
|     9|        1|           audi 4000|     gas|     turbo|      four|      sedan|       fwd|         front|    105.8|    192.7|    71.4|     55.9|      3086|       ohc|          five|       131|      mpfi|     3.13|   3.4|             8.3|       140|   5500|     17|        20|    23875|
|    10|        0| audi 5000s (diesel)|     gas|     turbo|       two|  hatchback|       4wd|         front|     99.5|    178.2|    67.9|       52|      3053|       ohc|          five|       131|      mpfi|     3.13|   3.4|               7|       160|   5500|     16|        22|17859.167|
|    11|        2|            bmw 320i|     gas|       std|       two|      sedan|       rwd|         front|    101.2|    176.8|    64.8|     54.3|      2395|       ohc|          four|       108|      mpfi|      3.5|   2.8|             8.8|       101|   5800|     23|        29|    16430|
|    12|        0|            bmw 320i|     gas|       std|      four|      sedan|       rwd|         front|    101.2|    176.8|    64.8|     54.3|      2395|       ohc|          four|       108|      mpfi|      3.5|   2.8|             8.8|       101|   5800|     23|        29|    16925|
|    13|        0|              bmw x1|     gas|       std|       two|      sedan|       rwd|         front|    101.2|    176.8|    64.8|     54.3|      2710|       ohc|           six|       164|      mpfi|     3.31|  3.19|               9|       121|   4250|     21|        28|    20970|
|    14|        0|              bmw x3|     gas|       std|      four|      sedan|       rwd|         front|    101.2|    176.8|    64.8|     54.3|      2765|       ohc|           six|       164|      mpfi|     3.31|  3.19|               9|       121|   4250|     21|        28|    21105|
|    15|        1|              bmw z4|     gas|       std|      four|      sedan|       rwd|         front|    103.5|      189|    66.9|     55.7|      3055|       ohc|           six|       164|      mpfi|     3.31|  3.19|               9|       121|   4250|     20|        25|    24565|
|    16|        0|              bmw x4|     gas|       std|      four|      sedan|       rwd|         front|    103.5|      189|    66.9|     55.7|      3230|       ohc|           six|       209|      mpfi|     3.62|  3.39|               8|       182|   5400|     16|        22|    30760|
|    17|        0|              bmw x5|     gas|       std|       two|      sedan|       rwd|         front|    103.5|    193.8|    67.9|     53.7|      3380|       ohc|           six|       209|      mpfi|     3.62|  3.39|               8|       182|   5400|     16|        22|    41315|
|    18|        0|              bmw x3|     gas|       std|      four|      sedan|       rwd|         front|      110|      197|    70.9|     56.3|      3505|       ohc|           six|       209|      mpfi|     3.62|  3.39|               8|       182|   5400|     15|        20|    36880|
|    19|        2|    chevrolet impala|     gas|       std|       two|  hatchback|       fwd|         front|     88.4|    141.1|    60.3|     53.2|      1488|         l|         three|        61|      2bbl|     2.91|  3.03|             9.5|        48|   5100|     47|        53|     5151|
+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+---------+
only showing top 20 rows

In [14]:
df_1=spark.read.option('header','True').csv('/content/drive/MyDrive/Colab Notebooks/CarPrice_Assignment (1).csv')

In [15]:
#We can select a specific column for analysis purpose, by passing argument count in the show we can select limited record

In [16]:
df_1.columns

['car_ID',
 'symboling',
 'CarName',
 'fueltype',
 'aspiration',
 'doornumber',
 'carbody',
 'drivewheel',
 'enginelocation',
 'wheelbase',
 'carlength',
 'carwidth',
 'carheight',
 'curbweight',
 'enginetype',
 'cylindernumber',
 'enginesize',
 'fuelsystem',
 'boreratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'citympg',
 'highwaympg',
 'price']

In [17]:
df_1.select('CarName','fueltype','highwaympg','price').show(10)

+--------------------+--------+----------+---------+
|             CarName|fueltype|highwaympg|    price|
+--------------------+--------+----------+---------+
|  alfa-romero giulia|     gas|        27|    13495|
| alfa-romero stelvio|     gas|        27|    16500|
|alfa-romero Quadr...|     gas|        26|    16500|
|         audi 100 ls|     gas|        30|    13950|
|          audi 100ls|     gas|        22|    17450|
|            audi fox|     gas|        25|    15250|
|          audi 100ls|     gas|        25|    17710|
|           audi 5000|     gas|        25|    18920|
|           audi 4000|     gas|        20|    23875|
| audi 5000s (diesel)|     gas|        22|17859.167|
+--------------------+--------+----------+---------+
only showing top 10 rows

In [18]:
df_1.describe().show()

+-------+-----------------+------------------+------------+--------+----------+----------+-----------+----------+--------------+------------------+------------------+-----------------+------------------+------------------+----------+--------------+------------------+----------+-------------------+-------------------+------------------+-----------------+-----------------+-----------------+-----------------+------------------+
|summary|           car_ID|         symboling|     CarName|fueltype|aspiration|doornumber|    carbody|drivewheel|enginelocation|         wheelbase|         carlength|         carwidth|         carheight|        curbweight|enginetype|cylindernumber|        enginesize|fuelsystem|          boreratio|             stroke|  compressionratio|       horsepower|          peakrpm|          citympg|       highwaympg|             price|
+-------+-----------------+------------------+------------+--------+----------+----------+-----------+----------+--------------+------------------+------------------+-----------------+------------------+------------------+----------+--------------+------------------+----------+-------------------+-------------------+------------------+-----------------+-----------------+-----------------+-----------------+------------------+
|  count|              205|               205|         205|     205|       205|       205|        205|       205|           205|               205|               205|              205|               205|               205|       205|           205|               205|       205|                205|                205|               205|              205|              205|              205|              205|               205|
|   mean|            103.0|0.8341463414634146|        null|    null|      null|      null|       null|      null|          null| 98.75658536585378|174.04926829268305|65.90780487804875|53.724878048780525|2555.5658536585365|      null|          null|126.90731707317073|      null| 3.3297560975609772|  3.255414634146336|10.142536585365855|104.1170731707317|5125.121951219512|25.21951219512195|30.75121951219512|13276.710570731706|
| stddev|59.32256456582661|1.2453068281055295|        null|    null|      null|      null|       null|      null|          null|6.0217756850255695|12.337288526555188|2.145203852687182| 2.443521969904905| 520.6802035016384|      null|          null|41.642693438179855|      null|0.27084370542622915|0.31359701376080396|3.9720403218632985|39.54416680936115|476.9856430569459| 6.54214165300162|6.886443130941823| 7988.852331743147|
|    min|                1|                -1|Nissan versa|  diesel|       std|      four|convertible|       4wd|         front|             100.4|             141.1|             60.3|              47.8|              1488|      dohc|         eight|               103|      1bbl|               2.54|               2.07|                10|              100|             4150|               13|               16|             10198|
|    max|               99|                 3|   vw rabbit|     gas|     turbo|       two|      wagon|       rwd|          rear|              99.8|             208.1|             72.3|              59.8|              4066|     rotor|           two|                98|      spfi|               3.94|               4.17|               9.6|               97|             6600|               49|               54|              9995|
+-------+-----------------+------------------+------------+--------+----------+----------+-----------+----------+--------------+------------------+------------------+-----------------+------------------+------------------+----------+--------------+------------------+----------+-------------------+-------------------+------------------+-----------------+-----------------+-----------------+-----------------+------------------+

In [19]:
df_1.groupBy('citympg').count()     #It is used useful in retrieving all the elements of the row from each partition

DataFrame[citympg: string, count: bigint]

In [20]:
df_1.groupBy("price","CarName").avg().collect()

[Row(price='5399', CarName='honda civic'),
 Row(price='10698', CarName='toyota celica gt'),
 Row(price='17669', CarName='toyota cressida'),
 Row(price='9295', CarName='renault 12tl'),
 Row(price='13295', CarName='volkswagen rabbit'),
 Row(price='5195', CarName='maxda rx3'),
 Row(price='5572', CarName='plymouth fury iii'),
 Row(price='8013', CarName='subaru dl'),
 Row(price='18920', CarName='audi 5000'),
 Row(price='6529', CarName='honda accord cvcc'),
 Row(price='7295', CarName='honda accord lx'),
 Row(price='10795', CarName='mazda glc deluxe'),
 Row(price='15645', CarName='mazda glc 4'),
 Row(price='16558', CarName='toyota corolla liftback'),
 Row(price='35056', CarName='buick skylark'),
 Row(price='12170', CarName='saab 99le'),
 Row(price='7689', CarName='mitsubishi g4'),
 Row(price='12629', CarName='mitsubishi outlander'),
 Row(price='18150', CarName='peugeot 604sl'),
 Row(price='7126', CarName='subaru'),
 Row(price='8189', CarName='mitsubishi pajero'),
 Row(price='8449', CarName='toyota corona liftback'),
 Row(price='7995', CarName='volkswagen model 111'),
 Row(price='12290', CarName='volkswagen dasher'),
 Row(price='7975', CarName='volkswagen 1131 deluxe sedan'),
 Row(price='6695', CarName='mazda rx-4'),
 Row(price='15985', CarName='volvo 244dl'),
 Row(price='6785', CarName='isuzu MU-X'),
 Row(price='13499', CarName='nissan otti'),
 Row(price='8558', CarName='dodge coronet custom'),
 Row(price='9538', CarName='toyota corolla tercel'),
 Row(price='7053', CarName='subaru dl'),
 Row(price='8916.5', CarName='isuzu D-Max V-Cross'),
 Row(price='31600', CarName='buick skyhawk'),
 Row(price='6488', CarName='toyota corolla 1200'),
 Row(price='8921', CarName='plymouth valiant'),
 Row(price='6338', CarName='toyota corona'),
 Row(price='6989', CarName='mitsubishi montero'),
 Row(price='10898', CarName='toyota corolla'),
 Row(price='10945', CarName='mazda 626'),
 Row(price='7499', CarName='nissan latio'),
 Row(price='7895', CarName='honda accord'),
 Row(price='8495', CarName='volkswagen 411 (sw)'),
 Row(price='11048', CarName='isuzu D-Max '),
 Row(price='9298', CarName='toyota celica gt liftback'),
 Row(price='8495', CarName='mazda glc custom l'),
 Row(price='7999', CarName='nissan note'),
 Row(price='9495', CarName='volkswagen super beetle'),
 Row(price='19699', CarName='nissan kicks'),
 Row(price='9095', CarName='honda civic 1300'),
 Row(price='10345', CarName='honda civic (auto)'),
 Row(price='7609', CarName='dodge colt (sw)'),
 Row(price='6669', CarName='mitsubishi outlander'),
 Row(price='6795', CarName='mazda rx2 coupe'),
 Row(price='10245', CarName='mazda rx-4'),
 Row(price='28248', CarName='buick century luxus (sw)'),
 Row(price='8195', CarName='volkswagen type 3'),
 Row(price='24565', CarName='bmw z4'),
 Row(price='18344', CarName='mazda rx-7 gs'),
 Row(price='5118', CarName='subaru'),
 Row(price='11845', CarName='mazda glc'),
 Row(price='17950', CarName='peugeot 504'),
 Row(price='21105', CarName='bmw x3'),
 Row(price='20970', CarName='bmw x1'),
 Row(price='35550', CarName='jaguar xf'),
 Row(price='11900', CarName='peugeot 504'),
 Row(price='7788', CarName='toyota corolla'),
 Row(price='6849', CarName='nissan latio'),
 Row(price='7198', CarName='toyota corolla 1200'),
 Row(price='16845', CarName='volvo 145e (sw)'),
 Row(price='7299', CarName='nissan leaf'),
 Row(price='30760', CarName='bmw x4'),
 Row(price='13200', CarName='peugeot 304'),
 Row(price='28176', CarName='buick century'),
 Row(price='41315', CarName='bmw x5'),
 Row(price='10295', CarName='honda accord'),
 Row(price='13495', CarName='alfa-romero giulia'),
 Row(price='5151', CarName='chevrolet impala'),
 Row(price='8249', CarName='nissan clipper'),
 Row(price='9233', CarName='subaru r1'),
 Row(price='8499', CarName='mitsubishi g4'),
 Row(price='11248', CarName='toyota mark ii'),
 Row(price='7295', CarName='honda civic 1500 gl'),
 Row(price='7898', CarName='toyota corolla 1600 (sw)'),
 Row(price='8778', CarName='toyota carina'),
 Row(price='15690', CarName='toyota starlet'),
 Row(price='18950', CarName='volvo diesel'),
 Row(price='12964', CarName='dodge coronet custom (sw)'),
 Row(price='37028', CarName='porsche boxter'),
 Row(price='9960', CarName='subaru baja'),
 Row(price='13645', CarName='mazda rx-7 gs'),
 Row(price='12764', CarName='plymouth duster'),
 Row(price='19045', CarName='volvo 144ea'),
 Row(price='12940', CarName='volvo 145e (sw)'),
 Row(price='7609', CarName='plymouth fury gran sedan'),
 Row(price='6479', CarName='honda civic'),
 Row(price='13499', CarName='nissan dayz'),
 Row(price='16515', CarName='volvo 245'),
 Row(price='23875', CarName='audi 4000'),
 Row(price='8949', CarName='nissan rogue'),
 Row(price='32250', CarName='jaguar xj'),
 Row(price='16900', CarName='peugeot 604sl'),
 Row(price='16503', CarName='mercury cougar'),
 Row(price='6377', CarName='dodge challenger se'),
 Row(price='5499', CarName='Nissan versa'),
 Row(price='14489', CarName='mitsubishi mirage g4'),
 Row(price='6229', CarName='plymouth fury iii'),
 Row(price='15040', CarName='saab 99le'),
 Row(price='8238', CarName='toyota corona'),
 Row(price='7775', CarName='subaru brz'),
 Row(price='18150', CarName='saab 99gle'),
 Row(price='9989', CarName='toyota starlet'),
 Row(price='7129', CarName='honda civic cvcc'),
 Row(price='22470', CarName='volvo 246'),
 Row(price='8845', CarName='mazda 626'),
 Row(price='5572', CarName='dodge rampage'),
 Row(price='6692', CarName='dodge colt hardtop'),
 Row(price='6855', CarName='honda civic cvcc'),
 Row(price='6095', CarName='maxda glc deluxe'),
 Row(price='22018', CarName='porsche macan'),
 Row(price='45400', CarName='buick regal sport coupe (turbo)'),
 Row(price='22625', CarName='volvo 264gl'),
 Row(price='10595', CarName='mazda glc custom'),
 Row(price='13845', CarName='volkswagen rabbit custom'),
 Row(price='25552', CarName='buick electra 225 custom'),
 Row(price='17710', CarName='audi 100ls'),
 Row(price='9895', CarName='renault 5 gtl'),
 Row(price='15510', CarName='saab 99gle'),
 Row(price='15750', CarName='toyouta tercel'),
 Row(price='8916.5', CarName='isuzu D-Max '),
 Row(price='11259', CarName='subaru r2'),
 Row(price='21485', CarName='volvo 244dl'),
 Row(price='34184', CarName='buick opel isuzu deluxe'),
 Row(price='13860', CarName='peugeot 504'),
 Row(price='9980', CarName='vw rabbit'),
 Row(price='7898', CarName='toyota corona'),
 Row(price='7799', CarName='nissan juke'),
 Row(price='7463', CarName='subaru trezia'),
 Row(price='18620', CarName='saab 99e'),
 Row(price='11199', CarName='toyota tercel'),
 Row(price='6295', CarName='chevrolet monte carlo'),
 Row(price='9639', CarName='toyota corolla'),
 Row(price='17075', CarName='peugeot 505s turbo diesel'),
 Row(price='6189', CarName='mitsubishi lancer'),
 Row(price='6918', CarName='toyota corona hardtop'),
 Row(price='9988', CarName='toyota corona'),
 Row(price='9995', CarName='volkswagen dasher'),
 Row(price='18399', CarName='nissan clipper'),
 Row(price='11694', CarName='subaru dl'),
 Row(price='8845', CarName='honda prelude'),
 Row(price='14869', CarName='mitsubishi g4'),
 Row(price='16430', CarName='bmw 320i'),
 Row(price='9258', CarName='toyota mark ii'),
 Row(price='13415', CarName='volvo 144ea'),
 Row(price='14399', CarName='nissan fuga'),
 Row(price='7099', CarName='nissan gt-r'),
 Row(price='9279', CarName='mitsubishi mirage g4'),
 Row(price='17859.167', CarName='audi 5000s (diesel)'),
 Row(price='11549', CarName='toyota corolla'),
 Row(price='6692', CarName='plymouth satellite custom (sw)'),
 Row(price='17450', CarName='audi 100ls'),
 Row(price='8948', CarName='toyota corolla'),
 Row(price='16925', CarName='bmw 320i'),
 Row(price='17199', CarName='nissan teana'),
 Row(price='16500', CarName='alfa-romero Quadrifoglio'),
 Row(price='18420', CarName='volvo 264gl'),
 Row(price='15250', CarName='audi fox'),
 Row(price='12945', CarName='honda civic'),
 Row(price='31400.5', CarName='porsche cayenne'),
 Row(price='8921', CarName='dodge dart custom'),
 Row(price='15580', CarName='peugeot 504'),
 Row(price='12440', CarName='peugeot 504 (sw)'),
 Row(price='11850', CarName='saab 99e'),
 Row(price='15998', CarName='toyota corona'),
 Row(price='8358', CarName='toyota corolla'),
 Row(price='11595', CarName='vw dasher'),
 Row(price='16500', CarName='alfa-romero stelvio'),
 Row(price='18280', CarName='mazda glc'),
 Row(price='7957', CarName='plymouth cricket'),
 Row(price='8058', CarName='toyota corolla liftback'),
 Row(price='7395', CarName='mazda glc deluxe'),
 Row(price='5348', CarName='toyota corona mark ii'),
 Row(price='6938', CarName='toyota mark ii'),
 Row(price='7349', CarName='nissan titan'),
 Row(price='9959', CarName='mitsubishi mirage g4'),
 Row(price='40960', CarName='buick century special'),
 Row(price='16695', CarName='peugeot 504'),
 Row(price='16630', CarName='peugeot 504'),
 Row(price='7603', CarName='subaru dl'),
 Row(price='13950', CarName='audi 100 ls'),
 Row(price='11245', CarName='mazda 626'),
 Row(price='10198', CarName='subaru tribeca'),
 Row(price='6649', CarName='nissan rogue'),
 Row(price='5389', CarName='mitsubishi mirage'),
 Row(price='36880', CarName='bmw x3'),
 Row(price='6229', CarName='dodge monaco (sw)'),
 Row(price='7775', CarName='vokswagen rabbit'),
 Row(price='7957', CarName='dodge d200'),
 Row(price='32528', CarName='porcshce panamera'),
 Row(price='36000', CarName='jaguar xk'),
 Row(price='9549', CarName='nissan nv200'),
 Row(price='34028', CarName='porsche cayenne'),
 Row(price='9279', CarName='mitsubishi outlander'),
 Row(price='6575', CarName='chevrolet vega 2300'),
 Row(price='7738', CarName='toyota corona')]

In [21]:
df_1.schema    #A schema is the description of the structure of your data (which together create a Dataset in Spark SQL).

StructType(List(StructField(car_ID,StringType,true),StructField(symboling,StringType,true),StructField(CarName,StringType,true),StructField(fueltype,StringType,true),StructField(aspiration,StringType,true),StructField(doornumber,StringType,true),StructField(carbody,StringType,true),StructField(drivewheel,StringType,true),StructField(enginelocation,StringType,true),StructField(wheelbase,StringType,true),StructField(carlength,StringType,true),StructField(carwidth,StringType,true),StructField(carheight,StringType,true),StructField(curbweight,StringType,true),StructField(enginetype,StringType,true),StructField(cylindernumber,StringType,true),StructField(enginesize,StringType,true),StructField(fuelsystem,StringType,true),StructField(boreratio,StringType,true),StructField(stroke,StringType,true),StructField(compressionratio,StringType,true),StructField(horsepower,StringType,true),StructField(peakrpm,StringType,true),StructField(citympg,StringType,true),StructField(highwaympg,StringType,true),StructField(price,StringType,true)))

In [22]:
from pyspark.sql.types import StructField, StructType, StringType, LongType

In [23]:
import pyspark.sql.functions as F

In [24]:
df_1.select('CarName').show(10)

+--------------------+
|             CarName|
+--------------------+
|  alfa-romero giulia|
| alfa-romero stelvio|
|alfa-romero Quadr...|
|         audi 100 ls|
|          audi 100ls|
|            audi fox|
|          audi 100ls|
|           audi 5000|
|           audi 4000|
| audi 5000s (diesel)|
+--------------------+
only showing top 10 rows

In [25]:
df_1.filter(F.col('fueltype')=='gas').show(5)      # filtering

+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+
|car_ID|symboling|             CarName|fueltype|aspiration|doornumber|    carbody|drivewheel|enginelocation|wheelbase|carlength|carwidth|carheight|curbweight|enginetype|cylindernumber|enginesize|fuelsystem|boreratio|stroke|compressionratio|horsepower|peakrpm|citympg|highwaympg|price|
+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+
|     1|        3|  alfa-romero giulia|     gas|       std|       two|convertible|       rwd|         front|     88.6|    168.8|    64.1|     48.8|      2548|      dohc|          four|       130|      mpfi|     3.47|  2.68|               9|       111|   5000|     21|        27|13495|
|     2|        3| alfa-romero stelvio|     gas|       std|       two|convertible|       rwd|         front|     88.6|    168.8|    64.1|     48.8|      2548|      dohc|          four|       130|      mpfi|     3.47|  2.68|               9|       111|   5000|     21|        27|16500|
|     3|        1|alfa-romero Quadr...|     gas|       std|       two|  hatchback|       rwd|         front|     94.5|    171.2|    65.5|     52.4|      2823|      ohcv|           six|       152|      mpfi|     2.68|  3.47|               9|       154|   5000|     19|        26|16500|
|     4|        2|         audi 100 ls|     gas|       std|      four|      sedan|       fwd|         front|     99.8|    176.6|    66.2|     54.3|      2337|       ohc|          four|       109|      mpfi|     3.19|   3.4|              10|       102|   5500|     24|        30|13950|
|     5|        2|          audi 100ls|     gas|       std|      four|      sedan|       4wd|         front|     99.4|    176.6|    66.4|     54.3|      2824|       ohc|          five|       136|      mpfi|     3.19|   3.4|               8|       115|   5500|     18|        22|17450|
+------+---------+--------------------+--------+----------+----------+-----------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+
only showing top 5 rows

In [26]:
df_1.where(F.col('fueltype')=='gas').where(F.col("CarName")=="audi 100 ls").show(5)      # multiple filtering

+------+---------+-----------+--------+----------+----------+-------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+
|car_ID|symboling|    CarName|fueltype|aspiration|doornumber|carbody|drivewheel|enginelocation|wheelbase|carlength|carwidth|carheight|curbweight|enginetype|cylindernumber|enginesize|fuelsystem|boreratio|stroke|compressionratio|horsepower|peakrpm|citympg|highwaympg|price|
+------+---------+-----------+--------+----------+----------+-------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+
|     4|        2|audi 100 ls|     gas|       std|      four|  sedan|       fwd|         front|     99.8|    176.6|    66.2|     54.3|      2337|       ohc|          four|       109|      mpfi|     3.19|   3.4|              10|       102|   5500|     24|        30|13950|
+------+---------+-----------+--------+----------+----------+-------+----------+--------------+---------+---------+--------+---------+----------+----------+--------------+----------+----------+---------+------+----------------+----------+-------+-------+----------+-----+

In [27]:
df_1.select('car_ID','symboling', 'CarName', 'fueltype', 'aspiration', 'doornumber',
       'carbody', 'drivewheel', 'enginelocation', 'wheelbase', 'carlength',
       'carwidth', 'carheight', 'curbweight', 'enginetype', 'cylindernumber',
       'enginesize', 'fuelsystem', 'boreratio', 'stroke', 'compressionratio',
       'horsepower', 'peakrpm', 'citympg', 'highwaympg', 'price').describe().show()

+-------+-----------------+------------------+------------+--------+----------+----------+-----------+----------+--------------+------------------+------------------+-----------------+------------------+------------------+----------+--------------+------------------+----------+-------------------+-------------------+------------------+-----------------+-----------------+-----------------+-----------------+------------------+
|summary|           car_ID|         symboling|     CarName|fueltype|aspiration|doornumber|    carbody|drivewheel|enginelocation|         wheelbase|         carlength|         carwidth|         carheight|        curbweight|enginetype|cylindernumber|        enginesize|fuelsystem|          boreratio|             stroke|  compressionratio|       horsepower|          peakrpm|          citympg|       highwaympg|             price|
+-------+-----------------+------------------+------------+--------+----------+----------+-----------+----------+--------------+------------------+------------------+-----------------+------------------+------------------+----------+--------------+------------------+----------+-------------------+-------------------+------------------+-----------------+-----------------+-----------------+-----------------+------------------+
|  count|              205|               205|         205|     205|       205|       205|        205|       205|           205|               205|               205|              205|               205|               205|       205|           205|               205|       205|                205|                205|               205|              205|              205|              205|              205|               205|
|   mean|            103.0|0.8341463414634146|        null|    null|      null|      null|       null|      null|          null| 98.75658536585378|174.04926829268305|65.90780487804875|53.724878048780525|2555.5658536585365|      null|          null|126.90731707317073|      null| 3.3297560975609772|  3.255414634146336|10.142536585365855|104.1170731707317|5125.121951219512|25.21951219512195|30.75121951219512|13276.710570731706|
| stddev|59.32256456582661|1.2453068281055295|        null|    null|      null|      null|       null|      null|          null|6.0217756850255695|12.337288526555188|2.145203852687182| 2.443521969904905| 520.6802035016384|      null|          null|41.642693438179855|      null|0.27084370542622915|0.31359701376080396|3.9720403218632985|39.54416680936115|476.9856430569459| 6.54214165300162|6.886443130941823| 7988.852331743147|
|    min|                1|                -1|Nissan versa|  diesel|       std|      four|convertible|       4wd|         front|             100.4|             141.1|             60.3|              47.8|              1488|      dohc|         eight|               103|      1bbl|               2.54|               2.07|                10|              100|             4150|               13|               16|             10198|
|    max|               99|                 3|   vw rabbit|     gas|     turbo|       two|      wagon|       rwd|          rear|              99.8|             208.1|             72.3|              59.8|              4066|     rotor|           two|                98|      spfi|               3.94|               4.17|               9.6|               97|             6600|               49|               54|              9995|
+-------+-----------------+------------------+------------+--------+----------+----------+-----------+----------+--------------+------------------+------------------+-----------------+------------------+------------------+----------+--------------+------------------+----------+-------------------+-------------------+------------------+-----------------+-----------------+-----------------+-----------------+------------------+

In [28]:
df_1.select('carbody').describe().show()

+-------+-----------+
|summary|    carbody|
+-------+-----------+
|  count|        205|
|   mean|       null|
| stddev|       null|
|    min|convertible|
|    max|      wagon|
+-------+-----------+